# Generated by Django 4.1.4 on 2022-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofeature', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='todofeature.label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
